# Euler Problem 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


fib_nums = []

a = 1
b = 0
c = 0
# 0, 1, 1, 2, 3, 5
while c < 4000000:
    c = a+b
    fib_nums.append(c)
    b = a
    a = c

sum = 0
for i in fib_nums:
    if i%2==0:
        sum += i

print(sum)
